### ISSUE TITLE
zone

### ISSUE THREAD

**Issue by azizonick** [erozedguy/Terraform-EKS-Cluster-with-Node-Group#1]
hey there, cant create recources in another zone, cold you pls tell how i can i? already changed the default zone value in version.tf file

**Comment by erozedguy** [comment]
hi

**Comment by erozedguy** [comment]
Hi,
- option 1: If you want to create the same resources in several regions you can use [alias: Multiple Provider Configurations](https://www.terraform.io/language/providers/configuration) 

- option 2: you can use [terragrunt ](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/). Define region as a variable in `version.tf`, and with terragrunt you can create .hcl files for each region and pass the name of the region as a variable
Acording the region you must change the AZS in `variables.tf`
- If you want to create in the same region but in several AZS, just add those AZS in `variables.tf`

**Comment by azizonick** [comment]
actually, i ve changed azs to mine, but it says you are alowed to create them only in us-east-1, but i ve mentioned eu-central-1
have you got any ideas about that?

**Comment by azizonick** [comment]
![image](https://user-images.githubusercontent.com/34322959/173957240-9eae191a-e619-4db3-a2a8-72ec955cbf01.png)

**Comment by azizonick** [comment]
![24c962d1-cbff-47a9-8acb-8165b4f92d89](https://user-images.githubusercontent.com/34322959/173957294-577c07bd-f28d-4299-9cb6-28d3c70b5258.jpg)

**Comment by erozedguy** [comment]
you must change the region in `versions.tf`
remove `us-east-1` and set `eu-central-1`

![image](https://user-images.githubusercontent.com/62074670/173960066-16c22d4e-4c82-4514-96f9-73d724cae5f2.png)
![image](https://user-images.githubusercontent.com/62074670/173960345-11a3329d-e646-4644-840a-c47f73578048.png)

**Comment by azizonick** [comment]
i know, and i already set them up, error is the same

**Comment by erozedguy** [comment]
ohhhh, i got it 
that's a problem with my vpc module

**Comment by azizonick** [comment]
okay, should i wait ?

**Comment by erozedguy** [comment]
depends on if you want to create a vpc and the eks cluster at same time
if u already have a vpc you can remove that module from main.tf and set your subnets directly in vpc_config
or u can wait, i will update that to set a region

**Comment by erozedguy** [comment]
what are you using this for?

**Comment by azizonick** [comment]
i want to create them at the same time, actually just tend to create eks from scratch for stg env

**Comment by azizonick** [comment]
okay waiting for you to update

**Comment by erozedguy** [comment]
ok, try to download the vpc module and terraform code to create cluster or fork them 
you must to check them and maintain them in your own repos
I won't maintain those repos constantly

**Comment by erozedguy** [comment]
I recommend u to create the vpc first and then the cluster
to maintain them

**Comment by erozedguy** [comment]
For now I updated those repos
U can use them but, take care using them hhahahha
